### ISSUE TITLE
CLion: infinite "Loading ..." status

### ISSUE THREAD

**Issue by silvioprog** [casteng/i-pascal#1]
Hello,

I'm trying to use i-Pascal in my CLion, however, it can't show any source kind, locked in the "Loading ..." status. Please see attached picture.

Thank you!
![screenshot_2017-01-17_13-50-57](https://cloud.githubusercontent.com/assets/1456829/22030547/af998a28-dcbc-11e6-9ab8-6f3f198acc1d.png)

**Comment by casteng** [comment]
There is some problems with other products like CLion or WebStorm.
Try this build, seems working:
http://www.siberika.com/download/IdeaPas.zip

**Comment by silvioprog** [comment]
This version worked like a charm. Thank you! :-)

**Comment by casteng** [comment]
You are welcome.
BTW, I-Pascal functionality is limited in CLion as it doesn't support SDKs and many other things.
