### ISSUE TITLE
Format ">=" "><" operator problem

### ISSUE THREAD

**Issue by tranleduy2000** [casteng/i-pascal#12]
Before format

![image](https://user-images.githubusercontent.com/19369448/27126419-956f5fae-5121-11e7-9410-9ee9f01ae54d.png)

After format

![image](https://user-images.githubusercontent.com/19369448/27126431-a2f8a07c-5121-11e7-900c-a654fda454a6.png)

**Comment by semoro** [comment]
`>=` fixed in https://github.com/casteng/i-pascal/pull/17

**Comment by casteng** [comment]
It's not fixed yet

**Comment by casteng** [comment]
Fixed in 1.50
