### ISSUE TITLE
Problem with generics

### ISSUE THREAD

**Issue by megahertz** [casteng/i-pascal#13]
I have a problem with FPC built-in fgl library.

If I add fgl source to Classpath, I-Pascal can't parse it correctly:
![fgl](https://user-images.githubusercontent.com/1762672/27423812-527f5dbc-574c-11e7-802a-d562adfdba04.png)

Also, I tried to add compiled fgl unit. But FPC compiles TFPGMap generic to TFPGMap$2 class, so I-Pascal can't recognize compiled TFPGMap$2 as TFPGMap.

**Comment by casteng** [comment]
Fixed parsing as well as .ppu issue in v1.50.

**Comment by megahertz** [comment]
Awesome! Thank you.
