### ISSUE TITLE
Selected directory is not valid SDK for Free pascal

### ISSUE THREAD

**Issue by WinterAlexander** [casteng/i-pascal#15]
I freshly installed the plugin and the compiler for pascal and restarted my computer. The plugin does not recognize the directory as home. Tried with different directories (parent and every children) and it did not seem to work.
Screenshot: [Imgur](http://imgur.com/a/NSuUb)

 I'm on Windows 7 64 bits. What should I do next to find what's causing the issue?

**Comment by megahertz** [comment]
Does the bin folder contain fpc.exe?

**Comment by WinterGuardian** [comment]
No, it contains only another folder i386-win32 that contains a few executables but no fpc.exe Will reinstall FPC. I have version 3.0.2 does it matter?

**Comment by WinterGuardian** [comment]
I've installed the 32 bits version on top of the 64 bits. That added the FPC IDE (I didn't have before) and it works for free Pascal ! There's still no fpc.exe into the bin folder though. And I would like to make it work for Delphi. Any idea?

**Comment by megahertz** [comment]
First of all, you need to find where's fpc.exe and specify its parent folder as sdk path.

I have no experience with I-Pascal and Delphi

**Comment by casteng** [comment]
What package you've used to install FPC? The one from here: https://www.freepascal.org/download.var
Or CodeTyphoon or something else?
For Delphi you should point to directory where it's installed. E.g. "c:\program files\Rad Studio\8.0".
