### ISSUE TITLE
TInvokeableVariantType support

### ISSUE THREAD

**Issue by megahertz** [casteng/i-pascal#19]
**Actual behaviour:**
![screenshot_20171113_133613](https://user-images.githubusercontent.com/1762672/32716445-e6a59960-c877-11e7-87a5-3f6d8670a6db.png)

**Expected behaviour:**
Do not mark access to members of variant type with "Undeclared identifier"

[More examples](https://synopse.info/files/html/Synopse%20mORMot%20Framework%20SAD%201.18.html#TITLE_37)

**Comment by casteng** [comment]
Fixed in 1.50

**Comment by megahertz** [comment]
Thank you very much! It works as expected, except for such case:
![test](https://user-images.githubusercontent.com/1762672/35573825-f2450b56-05f9-11e8-9968-2483fa79ad45.png)

**Comment by megahertz** [comment]
Unfortunately, it's broken again, I-Pascal 2.10
<img width="196" alt="variant" src="https://user-images.githubusercontent.com/1762672/52851337-4ad1d400-312f-11e9-966e-8edfdc03af62.png">
