### ISSUE TITLE
Problem with .ppu

### ISSUE THREAD

**Issue by megahertz** [casteng/i-pascal#20]
Sometimes there is a problem with complex .ppu which contains a lot of classes. For example, accessing to the Name property is marked as "Undeclared identifier" in the following code:

```pascal
WriteLn(User.GetProfile().Name)
```
It happens in situations, when in the decompiled .ppu the class TUser is defined before the class TProfile, like this:

**models.ppu:**
```pascal
{Decompiled unit interface}
unit models;
...
type TUser = class(system.TObject)
  public function GetProfile(): TProfile; { Also, go to declaration on TProfile doesn't work too }
...
type TProfile = class(system.TObject)
...
```
A such .ppu can be maked when code uses forward declaration, like https://github.com/casteng/i-pascal/issues/10#issuecomment-304944863

**Comment by casteng** [comment]
Can you attach an example xml output of ppudump for such a unit?

**Comment by megahertz** [comment]
Sure
[pas-test.zip](https://github.com/casteng/i-pascal/files/1729414/pas-test.zip)

**Comment by megahertz** [comment]
Works in 2.10, Thank you!
