### ISSUE TITLE
Breakpoints are ignored when running in debug mode

### ISSUE THREAD

**Issue by YourPsychiatrist** [casteng/i-pascal#21]
Whenever I add breakpoints within my program file and run the project in debug mode, the debugger runs through the whole program without suspension.

- The suspension checkbox is ticked in the breakpoint configuration
- The Free-Pascal SDK is set up properly (3.0.2)
- I made sure I am really running it in debug- instead of default mode

The console says 

> ~"(no debugging symbols found) ...done.\n"

**Comment by megahertz** [comment]
Did you try to add -gl flag to fpc?

**Comment by YourPsychiatrist** [comment]
Yes, in university we have to use the flags `-Mtp -gl -Criot`!

**Comment by megahertz** [comment]
You can try to play with other fpc -g* flags, depending on your environment

**Comment by YourPsychiatrist** [comment]
Sadly that didn't help. But i found a [stack trace](https://imgur.com/G4yNbBr) in the IntelliJ log, hopefully that helps.

**Comment by megahertz** [comment]
Unfortunately, Java, especially IntelliJ SDK in not my strong point.

**Comment by casteng** [comment]
Which version of the plugin and IntelliJ you are using?
The exception probably is not the problem cause.
This is:
> ~"(no debugging symbols found) ...done.\n"
Try to recompile source files.

**Comment by YourPsychiatrist** [comment]
IntelliJ: `2018.1 Public Preview`
Plugin: `v1.40`

Should I recompile the source files of my pascal program or the pascal plugin?

**Comment by casteng** [comment]
Please upgrade to I-Pascal v1.52.
Didn't tested the plugin in 2018 though.

2018-03-20 10:55 GMT+03:00, Niklas Vest <notifications@github.com>:
> IntelliJ: `2018.1 Public Preview`
> Plugin: `v1.40`
>
> Should I recompile the source files of my pascal program or the pascal
> plugin?
>
> --
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/casteng/i-pascal/issues/21#issuecomment-374506373


-- 

---
С уважением, Георгий
