### ISSUE TITLE
some autocomplete weirdness

### ISSUE THREAD

**Issue by Sorien** [casteng/i-pascal#23]
i have function (Delphi 2009, idea 2018.1.2 - cache cleared and rebuilded and all types bellow are properly resolved)

```pascal
func foo(); 
var
  wc: TWinControl;
begin
  wc. // autocomplete will give me suggestions only from TWinControl, TControl, TObject but not from TComponent and TPersistant 
  // as well 
  wc.FindComponent('foo') // FindComponent undeclared identifier
```
inheritence tree is TWinControl > TControl > TComponent  > TPersistant > TObject 

is there any inheritence limit?

**Comment by casteng** [comment]
No, there is no limit. Seems that unit (dcu?) where TComponent and TPersistent classes are declared us not parsed correctly.
