### ISSUE TITLE
Question: Which is the right way to add a local path with ppu files?

### ISSUE THREAD

**Issue by megahertz** [casteng/i-pascal#24]
I have a <project root>/Lib folder with *.o and *.ppu files

Now I need to add this path through FPC SDK Classpath which allows I-Pascal to recoginize these files correctly. Is it possible to add ./Lib path locally without changing global SDK settings?

**Comment by casteng** [comment]
At the moment adding directories with .ppu/.dcu to SDK classpath is the only way to add a library of compiled to project.

**Comment by megahertz** [comment]
Ok, thank you.
