### ISSUE TITLE
SDK setup not working on Linux

### ISSUE THREAD

**Issue by aksdb** [casteng/i-pascal#26]
A newly added SDK does neither find the compiler nor the classpath:
![ipascal_emptycompiler](https://user-images.githubusercontent.com/2435857/39524037-ff9f3e6e-4e17-11e8-8152-20917e00c612.png)

So I manually set the compiler and class path:
![ipascal_compilerset](https://user-images.githubusercontent.com/2435857/39524168-65058cd6-4e18-11e8-8358-6b01ab52dae4.png)

Yet all relevant units (Classes, SysUtils, etc.) are still not found ("undeclared identifier").

How is the SDK supposed to be setup?

**Comment by megahertz** [comment]
@aksdb try this conifg
![screenshot_20180502_194503](https://user-images.githubusercontent.com/1762672/39530045-8422e0fe-4e41-11e8-80b1-ee4508059b99.png)

**Comment by aksdb** [comment]
Looks better, although I had to invalidate the IntelliJ cache :-/
For whatever reason, "FreeAndNil" is not found. "Format" for example works, however. So something still doesn't quite add up.

**Comment by megahertz** [comment]
@aksdb https://bitbucket.org/argb32/i-pascal/issues/37/freeandnil-undeclared-identifier

**Comment by aksdb** [comment]
Ok then that's dealt with.
Anyway: is the classpath currently supposed to be populated manually? Could it maybe inferred from the fpc.cfg or the output from `fpc -va <somedummyprogram>`?

**Comment by megahertz** [comment]
In my case, this configuration was populated automatically, when I added a new SDK.

**Comment by casteng** [comment]
Base set of RTL units should be populated automatically.
How did you installed FPC? Is it a package which came from OS distro?
It's a little weird that units were placed in /opt/fpc/3.1.1/lib/fpc/3.1.1/units. Was it by default?
It's ok that compiler command field is empty. A default SDK binary will be used in that case.

**Comment by aksdb** [comment]
@casteng I usually install FPC via the packages provided on the FPC website, and specify `/opt/fpc/<version>` as install base directory. That way I can have multiple FPC versions side by side and easily switch by just modifying `$PATH`. (Also it is distribution agnostic so I can replicate that setup on all machines. Sometimes I am even forced to install in my home directory which will lead to a similar setup ... like for example `$HOME/fpc/<version>`.
