### ISSUE TITLE
High CPU usages

### ISSUE THREAD

**Issue by Sorien** [casteng/i-pascal#3]
Pls, could you look at this lib http://www.bilsen.com/gdiplus/GdiPlus1.2.zip opening GdiPlus.pas will raise CPU usage to 100% 

vesion 1.12

**Comment by casteng** [comment]
The unit is very large and contains many class/interface declarations.
The CPU usage is caused by searching for descendant classes and methods including the ones from other units.
After some optimization (stub index, etc) this will be much faster.

**Comment by casteng** [comment]
With stub indices the file can be handled in reasonable time. But it's still too big.
