### ISSUE TITLE
Website links broken and feedback on website does not work

### ISSUE THREAD

**Issue by michael-ring** [casteng/i-pascal#31]
The link from here to your website is broken, www.siberika.com does not work, only siberika.com works.

I tried to send some feedback from the siberika website but there's only a 
405 Not Allowed
nginx/1.10.3

error message

**Comment by jonathanfv** [comment]
This one is fixed (not sure I can close it though)

**Comment by ashumkin** [comment]
the issue is observed on 2.10
"Leave feedback" (http://www.siberika.com/siberika/ipascal.htm) and "Whats new"
 (http://www.siberika.com/siberika/whatsnew.htm) links are broken. Rather than http://www.siberika.com/ipascal.htm and http://www.siberika.com/whatsnew.htm, respectively
