### ISSUE TITLE
IntelliJ hangs when resolving merge conflicts in long pascal file

### ISSUE THREAD

**Issue by dagi12** [casteng/i-pascal#35]
Happens to me recently when resolving conflict in files with 2000+ . Everything is fine until you try to accept left/right side of 3-way merge tool. Then application hangs with 100% processor usage.

**Comment by casteng** [comment]
Is it reproducible? Can you please attach idea.log file which can be found with "Help->Show log..." just after the hang?

**Comment by casteng** [comment]
Fixed some deadlocks in v.2.20
