### ISSUE TITLE
How can I work with vcl or lcl? 

### ISSUE THREAD

**Issue by wangkai2014** [casteng/i-pascal#36]
I want to  use this plugin to develop GUI application, but It seems don't support use vcl and lcl, is it right?

**Comment by jonathanfv** [comment]
Do you mean you're looking for a GUI (DFM) editor? If so, unless I'm terribly mistaken, no, there's currently no editor. You could of course build a GUI from code.

**Comment by casteng** [comment]
GUI applications can be developed with I-Pascal as code editing will be needed anyway. But you probably need a form designer. Those are good in both Delphi and Lazarus so no point in reinventing the wheel.
