### ISSUE TITLE
Dependencies setup

### ISSUE THREAD

**Issue by PictureWilly** [casteng/i-pascal#37]
Following your nice development of I-Pascal for some time, but I can't get it really to work.

How can I get my Lazarus project work with I-Pascal with all the dependencies like LCL or other packages (.lpk) files. I simply don't understand how I set up these dependencies as their own modules or libraries so all required units are found.

I guess that's what the previous issue is actually about. 

A guide on how to setup all project dependencies in a structured way would be great.

**Comment by casteng** [comment]
Instruction on how to setup a project can be found here:
http://siberika.com/install.htm
Once you have SDK and a project with at least one module, you can add your dependencies.
It's simple enough - all directories with source files which you will not modify (library) should be added in Sourcepath of SDK. Sources which you want to modify should be marked as source in Source tab of a module. You can create separate module for each dependency and add them as a module dependency in main module.
Or use one module. In latter case all source directories should be within one directory which should be added as a content root. As in case with multiple modules all source directories should be marked as source.

**Comment by PictureWilly** [comment]
Thank you!
> all directories with source files which you will not modify (library) should be added in Sourcepath of SDK. 

You mean the **Classpath** of the SDK, as the Sourcepath is, according to the [documentation](http://siberika.com/install.htm), not used yet.

So the actual IntelliJ **Libraries** concept, including **Global Libraries**, in the "Project Structure" is not supported at all, only **Modules**.  Could you please confirm this.

**Comment by casteng** [comment]
My bad and you are right  - classpath of the SDK. Libraries and global libraries are not supported yet.
There is a little mess as at the moment when this part of the plugin was developed IDEA didn't support libraries or library sources for custom languages. Now it seems got this support for a while so this will be in the plugin someday.

**Comment by PictureWilly** [comment]
Aha, I see. It is quite confusing if you already worked with complex Java projects in IntelliJ. 
Real pascal libraries / package support would great!

For you info your **contact form** on http://siberika.com/ipascal.htm is not working. It returns error 405 for http://siberika.com/feedback.php
