### ISSUE TITLE
Run/Debug plugin

### ISSUE THREAD

**Issue by bubuker** [casteng/i-pascal#39]
Hello
I'm trying to tinker with plugin but i cant figure out how to run and debug it.

After importing the plugin project i'm trying to run and debug it. 
But Run/Debug configuration for plugin does not have **Use classpath of module** .
Am i missing something?

**Comment by casteng** [comment]
Have you enabled "plugin devKit" plugin?
The Run configuration should be of type "plugin" which is available if plugin devkit is enabled.

**Comment by bubuker** [comment]
I do have plugin DevKit installed:
![screenshot from 2019-02-23 20-58-36](https://user-images.githubusercontent.com/2780532/53289952-90854100-37ae-11e9-8f5e-bd30e696d61d.png)

So I have imported project from github repository and tried to debug:
![screenshot from 2019-02-23 21-01-49](https://user-images.githubusercontent.com/2780532/53290027-ac3d1700-37af-11e9-98c3-77d18ddc3a12.png)

But **Use classpath of module** is empty and there is no option in combo box.

**Comment by casteng** [comment]
Seems that module Plugin not imported correctly. It should be of plugin type and have corresponding icon in project view.
