### ISSUE TITLE
Undeclared identifier if number of arguments isn't match

### ISSUE THREAD

**Issue by megahertz** [casteng/i-pascal#41]
<img width="507" alt="DefArgs" src="https://user-images.githubusercontent.com/1762672/56600280-61058000-6609-11e9-9a9e-a1dc663d4d4e.png">

The error goes away when there is a third argument when calling. It appears in v2.20, there was no such a problem in v2.10.

**Comment by casteng** [comment]
This caused by lack of default parameters support in v2.20. It's already added in not yet released v2.30.
If it annoys you it can be downloaded:
http://www.siberika.com/downloads/ipascal.zip

**Comment by megahertz** [comment]
Thank you, v2.30 works correctly.
