### ISSUE TITLE
Type errors are not detected 

### ISSUE THREAD

**Issue by jakobmats** [casteng/i-pascal#48]
When you try to compile this code you'll get a type error. However, there are no inspections available that could catch it.

```Pascal
program MyProgram;
var
  Str: string;
begin
  Str := 1.0;
end.
```

`fpc` detects such issues at compile time so technically it would be possible to parse compiler output and mark errors in the editor.

**Comment by casteng** [comment]
This is already done and will be available in next release.

**Comment by jakobmats** [comment]
The latest version available to download on the web page is 2.55 but the changelog lists features up to version 2.60. Is there any way I can download 2.60?

**Comment by casteng** [comment]
Not yet.
2.60 will be released soon.

**Comment by casteng** [comment]
v2.60 just released. Highlight hints and warnings as well.
