### ISSUE TITLE
'&' unexpected

### ISSUE THREAD

**Issue by silvioprog** [casteng/i-pascal#5]
Hello,

Both Delphi and FPC allows the ampersand (`&`) to specify a reserved word as an identifier. Please see:

1. http://www.freepascal.org/docs-html/ref/refse4.html#x15-140001.4
2. http://docs.embarcadero.com/products/rad_studio/delphiAndcpp2009/HelpUpdate2/EN/html/devcommon/fundamentalsyntacticelementsov_xml.html#5468652044656C706869204368617261637465722053657420616E642042617369632053796E746178

Thank you!

**Comment by casteng** [comment]
Fixed in 1.24
