### ISSUE TITLE
Form Designer

### ISSUE THREAD

**Issue by michaelhonan** [casteng/i-pascal#51]
Any plans to support a form designer? Even if it's extremely basic.

Thanks so much for this effort, by the way!

**Comment by jonathanfv** [comment]
I'm not the main maintainer and I've contributed very little code to the project, but when I saw your request, I gave it a thought.
And I would tell you it's very unlikely to happen. The form designer heavily relies on compiled code, meaning you would need to develop a software host to run outside of IDEA (or even worse, a virtual machine to run inside the java VM). If IDEA was written in let's say C, that would become a lot easier. JNI could be used though.

Anyway, just my 2 cents: it's not going to happen anytime soon and is a major task, even for a simple one (unless a simple one only lets you choose the component class and their position on the form, without any proper rendering).

**Comment by michaelhonan** [comment]
@jonathanfv Definitely didn't expect a fully functional one like what's present in Delphi. I would totally work with a "barebones" DFM viewer which just shows bounding boxes with the component type printed inside.

Just an idea, happy to donate if something like this was ever considered. :)

**Comment by casteng** [comment]
No, there is no plans for form designer. The ones in Lazarus and Delphi are good enough.
If there was a stand alone form designed with say TCP/IP or REST interface I'd consider integration options.
