### ISSUE TITLE
Undeclared identifier in nested IFDEF macros

### ISSUE THREAD

**Issue by silvioprog** [casteng/i-pascal#6]
Hello,

Consider the following code:

```pascal
...
uses
  csize_t =
{$IFDEF FPC}
 {$IFDEF UNIX}
    BaseUnix
 {$ELSE}
    System
 {$ENDIF}
{$ELSE}
 {$IFDEF MSWINDOWS}
    Windows
 {$ELSE}
    SysTypes
 {$ENDIF}
{$ENDIF}.size_t;
...
```

Unfortunately i-pascal can't understand that, returning the error "Undeclared identifier", with red highlighting in two lines as showed in the picture below:

![screenshot_2017-04-12_15-53-31](https://cloud.githubusercontent.com/assets/1456829/24974417/7413488a-1f98-11e7-8c21-a3c43b79f790.png)

**Comment by casteng** [comment]
Which branch is correct? The one with "SysTypes"? Does it exists and available in source/library paths? If no you can set defines in SDK options with -Dxxx option.

**Comment by silvioprog** [comment]
See: [Delphi for Linux RTL units](http://blog.marcocantu.com/blog/2017-march-delphi-linux-rtl-units.html).

**Comment by casteng** [comment]
According to the blog post correct unit name for Linux is Posix.SysTypes.
Anyway the unit should be visible to the IDE via adding the directory with it to Project structure => SDK's => Classpath
