### ISSUE TITLE
Variadics support

### ISSUE THREAD

**Issue by silvioprog** [casteng/i-pascal#8]
Hello masters,

It would be nice to i-pascal to allow the `varargs` keyword.

Thank you!

**Comment by casteng** [comment]
It allows but may be not everywhere. It's hard to figure out real syntax of routine directives. Documentation on this topic isn't detailed and seems incorrect. Which compilable code isn't accepted by I-Pascal?
I found and fixed procedural type declarations case.

**Comment by casteng** [comment]
Please reopen if the problem still exists.
